backend:
  name: github
  repo: amitkumary96/amitkyadav.com
  branch: master
  base_url: https://api.github.com
  site_domain: amitkyadav.com
  client_id: Ov23lif7ssUuwSwcMIvP
  client_secret: a6f0c7812b64b2530012f6adaf358034dbcb4127
  auth_scope: repo
  api_root: https://api.github.com

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "poet"
    label: "Poet"
    folder: "src/content/poet"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "category", label: "Category", widget: "hidden", default: "poet" }
      - { name: "excerpt", label: "Excerpt", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "engineer"
    label: "Engineer"
    folder: "src/content/engineer"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "category", label: "Category", widget: "hidden", default: "engineer" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "excerpt", label: "Excerpt", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "life"
    label: "Life"
    folder: "src/content/life"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "category", label: "Category", widget: "hidden", default: "life" }
      - { name: "excerpt", label: "Excerpt", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
